# Numpy

In [106]:
import numpy as np

storages = [24, 3, 4 , 23, 10, 12]

print(storages)

np_storage = np.array(storages)

print(type(np_storage))

[24, 3, 4, 23, 10, 12]
<class 'numpy.ndarray'>


In [107]:
import numpy as np

arr = np.array([2, 5, 3, 4, 8])

print(arr + arr)

print(arr - arr)

print(arr * 3)

print(1 / arr)

[ 4 10  6  8 16]
[0 0 0 0 0]
[ 6 15  9 12 24]
[0.5        0.2        0.33333333 0.25       0.125     ]


## インデックス参照とスライス

In [108]:
import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [109]:
arr = np.arange(10)
arr[0:3] = 1

print(arr)

[1 1 1 3 4 5 6 7 8 9]


In [110]:
import numpy as np

arr = np.arange(10)
print(arr)

# 3,4,5だけ表示する
print(arr[3:6])

# 3,4,5 を 24 にする
arr[3:6] = 24
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[ 0  1  2 24 24 24  6  7  8  9]


In [111]:
import numpy as np

# ndarrayをそのまま別の変数に代入した場合の挙動を見る
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1
arr2[0] = 100

print(arr1)
print(arr2)

# ndarray を copy() を使って別の変数に代入した場合の挙動を見る
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1.copy()
arr2[0] = 100

print(arr1)
print(arr2)


[1 2 3 4 5]
[100   2   3   4   5]
[100   2   3   4   5]
[1 2 3 4 5]
[1 2 3 4 5]
[100   2   3   4   5]


## view と copy

In [112]:
import numpy as np

# Python の List型 の場合
arr_list = [x for x in range(10)]
print(arr_list)

arr_list_copy = arr_list[:]
arr_list_copy[0] = 100

print(arr_list)
print(arr_list_copy)


# Numpy の ndarray型の場合
arr_np = np.arange(10)
print(arr_np)

arr_np_view = arr_np[:]
arr_np_view[0] = 100

print(arr_np)
print(arr_np_view)

arr_np = np.arange(10)
print(arr_np)

arr_np_copy = arr_np[:].copy()
arr_np_copy[0] = 100

print(arr_np)
print(arr_np_copy)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[100, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]


## ブールインデックス参照

In [113]:
import numpy as np

arr = np.array([2, 4, 6, 7])

print(arr)
print(arr[np.array([True, True, False, True])])

[2 4 6 7]
[2 4 7]


In [114]:
import numpy as np

arr = np.array([2, 4, 6, 7])

print(arr[arr % 3 == 1])

[4 7]


In [115]:
import numpy as np

arr = np.array([2, 3, 4, 5, 6, 7])

print(arr % 2 == 0)

print(arr[arr % 2 == 0])

[ True False  True False  True False]
[2 4 6]


## ユニバーサル関数

In [116]:
import numpy as np


arr = np.array([4, -9, 16, -4, 20])

arr_abs = np.abs(arr)
print(arr_abs)

print( np.exp(arr_abs) )
print( np.sqrt(arr_abs) )

[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]


## 集合関数

In [117]:
import numpy as np

arr1 = [2, 5, 7, 9, 5, 2]
arr2 = [2, 5, 8, 3, 1]

new_arr1 = np.unique(arr1)
print(new_arr1)

print( np.union1d(arr1, arr2) )

[2 5 7 9]
[1 2 3 5 7 8 9]


## 乱数


In [118]:
import numpy as np
from numpy.random import rand, randint

# 0 以上 10 以内の整数の 5x2行列 を生成
arr1 = randint(0, 11, (5, 2))
print(arr1)

# 0 ~ 1 までの一様乱数を3つ生成
arr2 = rand(3)
print(arr2)



[[ 6  4]
 [ 8  4]
 [ 7 10]
 [ 4  3]
 [ 0  1]]
[0.55448096 0.2391703  0.00124204]


# 7.3 NumPyのよる2次元配列

In [119]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
])

print(arr)

print(arr.shape)

print(arr.reshape(4, 2))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 7.3.2 インデックス参照とスライス

In [120]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

print(arr[1])

print(arr[1, 2])
print(arr[1][2])

print(arr[1, 1:])
print(arr[1][1:])

[4 5 6]
6
6
[5 6]
[5 6]


In [121]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

print(arr)

print(arr[0, 2])

print(arr[1:, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[[4 5]
 [7 8]]


### 7.3.3 axis

In [122]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

21
[5 7 9]
[ 6 15]


In [123]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

print(arr.sum(axis=1))

[ 6 15 24]


### 7.3.4 ファンシーインデックス参照

In [124]:
import numpy as np

arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
])

print(arr[[3, 2, 0]])

[[7 8]
 [5 6]
 [1 2]]


In [125]:
import numpy as np

arr = np.arange(25).reshape(5, 5)
print(arr)

print(arr[[1, 3, 0]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


### 7.3.5 転置行列

In [126]:
import numpy as np

arr = np.arange(10).reshape(2, 5)
print(arr)

print(arr.T)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### 7.3.6 ソート

In [127]:
import numpy as np

arr = np.array([15, 30, 5])

arr.argsort()

print(arr[arr.argsort()])

[ 5 15 30]


In [128]:
import numpy as np

arr = np.array([
    [8, 4, 2],
    [3, 5, 1],
])

print(arr.argsort())

print(np.sort(arr))

arr.sort()
print(arr)

[[2 1 0]
 [2 0 1]]
[[2 4 8]
 [1 3 5]]
[[2 4 8]
 [1 3 5]]


### 7.3.7 行列計算

In [129]:
import numpy as np

arr = np.arange(9).reshape(3, 3)
print(arr)

print(arr.dot(arr, arr))

vec = arr.reshape(9)

print(np.linalg.norm(vec))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
187.63794925334267


### 7.3.8 統計関数

In [130]:
import numpy as np

arr = np.arange(15).reshape(3, 5)

print(arr)

# 列ごとに平均
print(np.average(arr, axis=0))

# 行の合計
print(np.sum(arr, axis=1))

# 最小値
print(np.min(arr))

# 列ごとの最大値をインデックス表示
print(np.argmax(arr, axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[5. 6. 7. 8. 9.]
[10 35 60]
0
[2 2 2 2 2]


### 7.3.9 ブロードキャスト

In [133]:
import numpy as np

x = np.arange(6).reshape(2, 3)

print(x)
print(x + 1)

[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]


In [135]:
import numpy as np

x = np.arange(15).reshape(3, 5)
print(x)

y = np.array([np.arange(5)])
print(y)

print(x - y )


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0 1 2 3 4]]
[[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]


## 添削問題

In [150]:
import numpy as np

np.random.seed(100)

arr = np.random.randint(0, 31, (5, 3))
print( arr )

# 行列の転置
arr = arr.T
print( arr )

arr1 = arr[:, 1:4]
print( arr1 )

arr1.sort(axis=1)
print( arr1 )

print( np.mean(arr1, axis=0) )

[[ 8 24  3]
 [ 7 23 15]
 [16 10 30]
 [20  2 21]
 [ 2  2 14]]
[[ 8  7 16 20  2]
 [24 23 10  2  2]
 [ 3 15 30 21 14]]
[[ 7 16 20]
 [23 10  2]
 [15 30 21]]
[[ 7 16 20]
 [ 2 10 23]
 [15 21 30]]
[ 8.         15.66666667 24.33333333]
